const datosNotas = {
"1101":[
 {
  "IEM Instituto Técnico Industrial": "Grupo: 1101, Grado: 11",
  "Column2": "Director: Hoyos Mahecha Ana Marisol"
 },
 {
  "IEM Instituto Técnico Industrial": "Periodo: 2 de 2024"
 },
 {
  "IEM Instituto Técnico Industrial": "Estudiante",
  "Column2": "Física",
  "Column3": "Quimica",
  "Column4": "Csociales",
  "Column5": "Econ y Pol",
  "Column6": "Artística",
  "Column7": "Ét y Rel",
  "Column8": "Edufísica",
  "Column9": "Lenguaje",
  "Column10": "Inglés",
  "Column11": "Matemáticas",
  "Column12": "Gempresarial",
  "Column13": "Tecnología",
  "Column14": "Filosofia",
  "Column15": "Taller",
  "Column16": "Convivencia",
  "Column17": "mRep",
  "Column18": "pEst"
 },
 {
  "IEM Instituto Técnico Industrial": "Acosta Díaz Laura Juliana",
  "Column2": "DS",
  "Column3": "DA",
  "Column4": "DA",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DA",
  "Column10": "DS",
  "Column11": "DS",
  "Column12": "DA",
  "Column13": "DS",
  "Column14": "DB",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 89
 },
 {
  "IEM Instituto Técnico Industrial": "Andrade Gómez Camila Estefanía",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DBJ",
  "Column10": "DA",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DB",
  "Column16": "DA",
  "Column17": 6,
  "Column18": 64
 },
 {
  "IEM Instituto Técnico Industrial": "Arias Mendoza Samuel Andrés",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DA",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DA",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DA",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": 1,
  "Column18": 80
 },
 {
  "IEM Instituto Técnico Industrial": "Benítez Ríos Diego Armando",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DBJ",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DA",
  "Column17": 8,
  "Column18": 58
 },
 {
  "IEM Instituto Técnico Industrial": "Bermúdez Salazar María Fernanda",
  "Column2": "DA",
  "Column3": "DA",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DB",
  "Column7": "DA",
  "Column8": "DS",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DA",
  "Column14": "DB",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 82
 },
 {
  "IEM Instituto Técnico Industrial": "Calderón Herrera Felipe Eduardo",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DA",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": 1,
  "Column18": 81
 },
 {
  "IEM Instituto Técnico Industrial": "Cárdenas Suárez Nicolás Alejandro",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DS",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": 1,
  "Column18": 79
 },
 {
  "IEM Instituto Técnico Industrial": "Castillo Luna Andrea Sofía",
  "Column2": "DA",
  "Column3": "DA",
  "Column4": "DA",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DA",
  "Column8": "DS",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DB",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 84
 },
 {
  "IEM Instituto Técnico Industrial": "Duarte Molina Tomás Ricardo",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DA",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DA",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": 1,
  "Column18": 83
 },
 {
  "IEM Instituto Técnico Industrial": "Escobar Vélez Daniela Lucía",
  "Column2": "DS",
  "Column3": "DS",
  "Column4": "DA",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DA",
  "Column10": "DS",
  "Column11": "DS",
  "Column12": "DS",
  "Column13": "DA",
  "Column14": "DB",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 90
 },
 {
  "IEM Instituto Técnico Industrial": "Fernández Aguilar Jorge Sebastián",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DA",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DA",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 2,
  "Column18": 74
 },
 {
  "IEM Instituto Técnico Industrial": "Figueroa Camacho Valentina Isabel",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DB",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DBJ",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 7,
  "Column18": 62
 },
 {
  "IEM Instituto Técnico Industrial": "Gaitán Lozano Javier Manuel",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DB",
  "Column16": "DA",
  "Column17": 5,
  "Column18": 65
 },
 {
  "IEM Instituto Técnico Industrial": "García Torres Paula Catalina",
  "Column2": "DB",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DB",
  "Column7": "DA",
  "Column8": "DS",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DA",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": 1,
  "Column18": 78
 },
 {
  "IEM Instituto Técnico Industrial": "Giraldo Peña Miguel Ángel",
  "Column2": "DB",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DA",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": 2,
  "Column18": 74
 },
 {
  "IEM Instituto Técnico Industrial": "Guzmán Romero Luis Alberto",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DS",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DA",
  "Column17": 6,
  "Column18": 65
 },
 {
  "IEM Instituto Técnico Industrial": "Herrera Quintero Ana Sofía",
  "Column2": "DA",
  "Column3": "DA",
  "Column4": "DA",
  "Column5": "DS",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DS",
  "Column9": "DS",
  "Column10": "DS",
  "Column11": "DS",
  "Column12": "DS",
  "Column13": "DB",
  "Column14": "DA",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 91
 },
 {
  "IEM Instituto Técnico Industrial": "López Vargas Sebastián Mateo",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DA",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DA",
  "Column14": "DA",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 80
 },
 {
  "IEM Instituto Técnico Industrial": "Martínez Silva Gabriela Renata",
  "Column2": "DS",
  "Column3": "DS",
  "Column4": "DA",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DS",
  "Column9": "DA",
  "Column10": "DS",
  "Column11": "DS",
  "Column12": "DS",
  "Column13": "DS",
  "Column14": "DS",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 94
 },
 {
  "IEM Instituto Técnico Industrial": "Medina Fajardo Ricardo Enrique",
  "Column2": "DBJ",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DBJ",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DB",
  "Column17": 12,
  "Column18": 49
 },
 {
  "IEM Instituto Técnico Industrial": "Mejía Cruz Santiago Esteban",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DS",
  "Column7": "DA",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DS",
  "Column11": "DA",
  "Column12": "DA",
  "Column13": "DA",
  "Column14": "DA",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 85
 },
 {
  "IEM Instituto Técnico Industrial": "Mendoza Castaño Elena Marcela",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DB",
  "Column16": "DS",
  "Column17": 2,
  "Column18": 73
 },
 {
  "IEM Instituto Técnico Industrial": "Molina Páez Carla Eugenia",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DB",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DB",
  "Column16": "DA",
  "Column17": 3,
  "Column18": 68
 },
 {
  "IEM Instituto Técnico Industrial": "Moreno Téllez Iván Leonardo",
  "Column2": "DS",
  "Column3": "DS",
  "Column4": "DA",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DS",
  "Column9": "DA",
  "Column10": "DS",
  "Column11": "DS",
  "Column12": "DS",
  "Column13": "DS",
  "Column14": "DS",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 94
 },
 {
  "IEM Instituto Técnico Industrial": "Navarro Bustos Óscar Daniel",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DA",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DA",
  "Column13": "DA",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": 1,
  "Column18": 78
 },
 {
  "IEM Instituto Técnico Industrial": "Ortega Beltrán Adriana Milena",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DA",
  "Column17": 5,
  "Column18": 62
 },
 {
  "IEM Instituto Técnico Industrial": "Paredes Niño Juan Esteban",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DA",
  "Column8": "DB",
  "Column9": "DA",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DS",
  "Column13": "DB",
  "Column14": "DB",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 82
 },
 {
  "IEM Instituto Técnico Industrial": "Rojas Pineda Emmanuel Josué",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DBJ",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DBJ",
  "Column13": "DA",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": 3,
  "Column18": 71
 },
 {
  "IEM Instituto Técnico Industrial": "TOTALES",
  "Column2": 1,
  "Column3": 8,
  "Column4": 1,
  "Column5": 1,
  "Column6": 3,
  "Column7": 2,
  "Column8": "-",
  "Column9": 5,
  "Column10": 3,
  "Column11": 6,
  "Column12": 8,
  "Column13": 7,
  "Column14": 18,
  "Column15": 4,
  "Column16": "-",
  "Column17": "..."
 },
 {
  "IEM Instituto Técnico Industrial": "Fecha de creación:2024-10-31 07-03"
 },
 {
  "IEM Instituto Técnico Industrial": "NotaEscolar "
 }
],
"1102":[
 {
  "IEM Instituto Técnico Industrial": "Grupo: 1102, Grado: 11",
  "Column2": "Director: Vivas Serna Donny"
 },
 {
  "IEM Instituto Técnico Industrial": "Periodo: 2 de 2024"
 },
 {
  "IEM Instituto Técnico Industrial": "Estudiante",
  "Column2": "Física",
  "Column3": "Quimica",
  "Column4": "Csociales",
  "Column5": "Econ y Pol",
  "Column6": "Artística",
  "Column7": "Ét y Rel",
  "Column8": "Edufísica",
  "Column9": "Lenguaje",
  "Column10": "Inglés",
  "Column11": "Matemáticas",
  "Column12": "Gempresarial",
  "Column13": "Tecnología",
  "Column14": "Filosofia",
  "Column15": "Taller",
  "Column16": "Convivencia",
  "Column17": "mRep",
  "Column18": "pEst"
 },
 {
  "IEM Instituto Técnico Industrial": "Aguilar Torres Camilo Sebastián",
  "Column2": "DB",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DA",
  "Column14": "DA",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 1,
  "Column18": 75
 },
 {
  "IEM Instituto Técnico Industrial": "Aldana Pineda Melany Carolina",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DBJ",
  "Column5": "DB",
  "Column6": "DBJ",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 8,
  "Column18": 58
 },
 {
  "IEM Instituto Técnico Industrial": "Álvarez Romero Sofía Valeria",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DA",
  "Column8": "DS",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": 1,
  "Column18": 80
 },
 {
  "IEM Instituto Técnico Industrial": "Amaya Castaño Pablo Emilio",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DA",
  "Column8": "DS",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DB",
  "Column17": 4,
  "Column18": 70
 },
 {
  "IEM Instituto Técnico Industrial": "Arango Guzmán Valeria Nicole",
  "Column2": "DB",
  "Column3": "DB",
  "Column4": "DBJ",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DB",
  "Column17": 4,
  "Column18": 69
 },
 {
  "IEM Instituto Técnico Industrial": "Ayala Márquez Leonardo David",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DBJ",
  "Column7": "DB",
  "Column8": "DBJ",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DS",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DB",
  "Column17": 8,
  "Column18": 60
 },
 {
  "IEM Instituto Técnico Industrial": "Barrios Ruiz Martina Alejandra",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 4,
  "Column18": 69
 },
 {
  "IEM Instituto Técnico Industrial": "Bautista Vargas Mateo Julián",
  "Column2": "DA",
  "Column3": "DS",
  "Column4": "DB",
  "Column5": "DS",
  "Column6": "DA",
  "Column7": "DS",
  "Column8": "DS",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DA",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 89
 },
 {
  "IEM Instituto Técnico Industrial": "Bello Carrillo Daniela Sofía",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DA",
  "Column5": "DB",
  "Column6": "DB",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DB",
  "Column16": "DA",
  "Column17": 6,
  "Column18": 62
 },
 {
  "IEM Instituto Técnico Industrial": "Buitrago Morales Juan David",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DB",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 8,
  "Column18": 57
 },
 {
  "IEM Instituto Técnico Industrial": "Cabrera Núñez Camila Alejandra",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DBJ",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DA",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 9,
  "Column18": 56
 },
 {
  "IEM Instituto Técnico Industrial": "Calderón Perea Emanuel Santiago",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 5,
  "Column18": 66
 },
 {
  "IEM Instituto Técnico Industrial": "Camargo Duarte Nicolás Esteban",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DS",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DA",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 86
 },
 {
  "IEM Instituto Técnico Industrial": "Cano Silva Juliana María",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DBJ",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 10,
  "Column18": 54
 },
 {
  "IEM Instituto Técnico Industrial": "Castaño Rivas Thiago Emanuel",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DB",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 86
 },
 {
  "IEM Instituto Técnico Industrial": "Cely Méndez Jorge Eduardo",
  "Column2": "DS",
  "Column3": "DA",
  "Column4": "DA",
  "Column5": "DS",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DS",
  "Column10": "DS",
  "Column11": "DA",
  "Column12": "DA",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DB",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 90
 },
 {
  "IEM Instituto Técnico Industrial": "Cruz Velásquez Isabella Antonella",
  "Column2": "DA",
  "Column3": "DA",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DS",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DB",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 86
 },
 {
  "IEM Instituto Técnico Industrial": "Delgadillo Acuña Andrés Felipe",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DB",
  "Column7": "DBJ",
  "Column8": "DBJ",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DB",
  "Column17": 9,
  "Column18": 55
 },
 {
  "IEM Instituto Técnico Industrial": "Díaz Bermúdez Luciana Gabriela",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DS",
  "Column7": "DB",
  "Column8": "DS",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DB",
  "Column16": "DB",
  "Column17": 8,
  "Column18": 60
 },
 {
  "IEM Instituto Técnico Industrial": "Espinosa León Ivanna Michelle",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DA",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 6,
  "Column18": 64
 },
 {
  "IEM Instituto Técnico Industrial": "Forero Niño Samuel Alejandro",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DBJ",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DB",
  "Column17": 12,
  "Column18": 49
 },
 {
  "IEM Instituto Técnico Industrial": "Galindo Cárdenas Emiliano José",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DA",
  "Column5": "DS",
  "Column6": "DS",
  "Column7": "DA",
  "Column8": "DB",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 86
 },
 {
  "IEM Instituto Técnico Industrial": "García Roldán María Camila",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DA",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DS",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DBJ",
  "Column14": "DA",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 1,
  "Column18": 82
 },
 {
  "IEM Instituto Técnico Industrial": "González Herrera Alan Benjamín",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DBJ",
  "Column8": "DS",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DS",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": 2,
  "Column18": 78
 },
 {
  "IEM Instituto Técnico Industrial": "Guerrero Fonseca Renata Isabella",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DB",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DA",
  "Column14": "DB",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 3,
  "Column18": 68
 },
 {
  "IEM Instituto Técnico Industrial": "León Trujillo Carlos Mauricio",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DA",
  "Column7": "DBJ",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 6,
  "Column18": 66
 },
 {
  "IEM Instituto Técnico Industrial": "Lozano Rodríguez Jerónimo Manuel",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DA",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DA",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": 1,
  "Column18": 76
 },
 {
  "IEM Instituto Técnico Industrial": "Maldonado Reyes Laura Valentina",
  "Column2": "DA",
  "Column3": "DA",
  "Column4": "DB",
  "Column5": "DS",
  "Column6": "DA",
  "Column7": "DA",
  "Column8": "DA",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DA",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 87
 },
 {
  "IEM Instituto Técnico Industrial": "TOTALES",
  "Column2": "-",
  "Column3": 14,
  "Column4": 9,
  "Column5": 8,
  "Column6": 5,
  "Column7": 8,
  "Column8": 2,
  "Column9": 9,
  "Column10": 3,
  "Column11": 15,
  "Column12": 14,
  "Column13": 9,
  "Column14": 18,
  "Column15": 2,
  "Column16": "-",
  "Column17": "..."
 },
 {
  "IEM Instituto Técnico Industrial": "Fecha de creación:2024-10-31 07-04"
 },
 {
  "IEM Instituto Técnico Industrial": "NotaEscolar "
 }
],
"1103":[
 {
  "IEM Instituto Técnico Industrial": "Grupo: 1103, Grado: 11",
  "Column2": "Director: Mendez Prada Aura Janneth"
 },
 {
  "IEM Instituto Técnico Industrial": "Periodo: 2 de 2024"
 },
 {
  "IEM Instituto Técnico Industrial": "Estudiante",
  "Column2": "Física",
  "Column3": "Quimica",
  "Column4": "Csociales",
  "Column5": "Econ y Pol",
  "Column6": "Artística",
  "Column7": "Ét y Rel",
  "Column8": "Edufísica",
  "Column9": "Lenguaje",
  "Column10": "Inglés",
  "Column11": "Matemáticas",
  "Column12": "Gempresarial",
  "Column13": "Tecnología",
  "Column14": "Filosofia",
  "Column15": "Taller",
  "Column16": "Convivencia",
  "Column17": "mRep",
  "Column18": "pEst"
 },
 {
  "IEM Instituto Técnico Industrial": "Acuña Moreno Isabella María",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DBJ",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DBJ",
  "Column10": "DA",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DB",
  "Column17": 7,
  "Column18": 59
 },
 {
  "IEM Instituto Técnico Industrial": "Agudelo Pineda Juan Sebastián",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DB",
  "Column16": "DB",
  "Column17": 7,
  "Column18": 59
 },
 {
  "IEM Instituto Técnico Industrial": "Andrade León Mariana Sofía",
  "Column2": "DA",
  "Column3": "DA",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DA",
  "Column10": "DS",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": 1,
  "Column18": 81
 },
 {
  "IEM Instituto Técnico Industrial": "Arias Ramírez Diego Alejandro",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DB",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DB",
  "Column17": 7,
  "Column18": 55
 },
 {
  "IEM Instituto Técnico Industrial": "Barrera Gómez Luciana Isabela",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DB",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DB",
  "Column17": 7,
  "Column18": 59
 },
 {
  "IEM Instituto Técnico Industrial": "Beltrán Torres Tomás Eduardo",
  "Column2": "DB",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DA",
  "Column7": "DA",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 2,
  "Column18": 72
 },
 {
  "IEM Instituto Técnico Industrial": "Bonilla Escobar Paula Valentina",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DS",
  "Column7": "DA",
  "Column8": "DA",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DA",
  "Column15": "DS",
  "Column16": "DB",
  "Column17": 1,
  "Column18": 77
 },
 {
  "IEM Instituto Técnico Industrial": "Cárdenas Montoya Nicolás Santiago",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DB",
  "Column17": 6,
  "Column18": 64
 },
 {
  "IEM Instituto Técnico Industrial": "Castañeda Romero Alan Gabriel",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DS",
  "Column8": "DS",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DB",
  "Column17": 4,
  "Column18": 69
 },
 {
  "IEM Instituto Técnico Industrial": "Chacón Duarte Laura Antonella",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DB",
  "Column15": "DS",
  "Column16": "DB",
  "Column17": "-",
  "Column18": 78
 },
 {
  "IEM Instituto Técnico Industrial": "Delgado Ruiz Mateo Emiliano",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DB",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DA",
  "Column15": "DS",
  "Column16": "DB",
  "Column17": "-",
  "Column18": 79
 },
 {
  "IEM Instituto Técnico Industrial": "Duarte Figueroa Camila Julieta",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 3,
  "Column18": 69
 },
 {
  "IEM Instituto Técnico Industrial": "Escamilla Prada Samuel Esteban",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DA",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": 1,
  "Column18": 78
 },
 {
  "IEM Instituto Técnico Industrial": "Farfán Rodríguez Valentina Sofía",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DS",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 6,
  "Column18": 64
 },
 {
  "IEM Instituto Técnico Industrial": "Gallego Barragán Emiliano Mateo",
  "Column2": "DB",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DS",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DA",
  "Column15": "DS",
  "Column16": "DB",
  "Column17": "-",
  "Column18": 77
 },
 {
  "IEM Instituto Técnico Industrial": "Jiménez Salinas Sofía Gabriela",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DA",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 10,
  "Column18": 54
 },
 {
  "IEM Instituto Técnico Industrial": "Londoño Cárdenas Santiago Alonso",
  "Column2": "DB",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DB",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DB",
  "Column17": 5,
  "Column18": 63
 },
 {
  "IEM Instituto Técnico Industrial": "Márquez Gutiérrez Ana María",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DA",
  "Column8": "DA",
  "Column9": "DBJ",
  "Column10": "DA",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DB",
  "Column17": 5,
  "Column18": 70
 },
 {
  "IEM Instituto Técnico Industrial": "Naranjo Cifuentes Gabriel Leonardo",
  "Column2": "DB",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DS",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 6,
  "Column18": 64
 },
 {
  "IEM Instituto Técnico Industrial": "Pérez Muñoz Martina Valeria",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DB",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DB",
  "Column16": "DB",
  "Column17": 8,
  "Column18": 57
 },
 {
  "IEM Instituto Técnico Industrial": "Ramírez Ortega Emmanuel Julián",
  "Column2": "DB",
  "Column3": "DB",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DB",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 4,
  "Column18": 66
 },
 {
  "IEM Instituto Técnico Industrial": "TOTALES",
  "Column2": "-",
  "Column3": 10,
  "Column4": 5,
  "Column5": 11,
  "Column6": 1,
  "Column7": 2,
  "Column8": "-",
  "Column9": 8,
  "Column10": 3,
  "Column11": 11,
  "Column12": 13,
  "Column13": 8,
  "Column14": 17,
  "Column15": 5,
  "Column16": "-",
  "Column17": "..."
 },
 {
  "IEM Instituto Técnico Industrial": "Fecha de creación:2024-10-31 07-04"
 },
 {
  "IEM Instituto Técnico Industrial": "NotaEscolar "
 }
],
"1104":[
 {
  "IEM Instituto Técnico Industrial": "Grupo: 1104, Grado: 11",
  "Column2": "Director: Baquero Romero Jair Alfonso"
 },
 {
  "IEM Instituto Técnico Industrial": "Periodo: 2 de 2024"
 },
 {
  "IEM Instituto Técnico Industrial": "Estudiante",
  "Column2": "Física",
  "Column3": "Quimica",
  "Column4": "Csociales",
  "Column5": "Econ y Pol",
  "Column6": "Artística",
  "Column7": "Ét y Rel",
  "Column8": "Edufísica",
  "Column9": "Lenguaje",
  "Column10": "Inglés",
  "Column11": "Matemáticas",
  "Column12": "Gempresarial",
  "Column13": "Tecnología",
  "Column14": "Filosofia",
  "Column15": "Taller",
  "Column16": "Convivencia",
  "Column17": "mRep",
  "Column18": "pEst"
 },
 {
  "IEM Instituto Técnico Industrial": "Acevedo Rincón Samuel Julián",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DA",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 2,
  "Column18": 75
 },
 {
  "IEM Instituto Técnico Industrial": "Alarcón Duarte Mariana Lucía",
  "Column2": "DBJ",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DA",
  "Column7": "DS",
  "Column8": "DBJ",
  "Column9": "DBJ",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DA",
  "Column17": 11,
  "Column18": 54
 },
 {
  "IEM Instituto Técnico Industrial": "Aparicio Vargas Tomás Felipe",
  "Column2": "DBJ",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DBJ",
  "Column9": "DBJ",
  "Column10": "DBJ",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 8,
  "Column18": 56
 },
 {
  "IEM Instituto Técnico Industrial": "Arévalo Suárez Ana Gabriela",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DA",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 2,
  "Column18": 78
 },
 {
  "IEM Instituto Técnico Industrial": "Barreto Lozano Nicolás Emanuel",
  "Column2": "DA",
  "Column3": "DS",
  "Column4": "DA",
  "Column5": "DS",
  "Column6": "DA",
  "Column7": "DA",
  "Column8": "DS",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DA",
  "Column13": "DA",
  "Column14": "DB",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": "-",
  "Column18": 85
 },
 {
  "IEM Instituto Técnico Industrial": "Becerra Niño Valeria Antonella",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DS",
  "Column14": "DB",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 1,
  "Column18": 81
 },
 {
  "IEM Instituto Técnico Industrial": "Bermúdez Cortés Daniel Santiago",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DS",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DA",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 2,
  "Column18": 78
 },
 {
  "IEM Instituto Técnico Industrial": "Cabrales Salinas Isabel Fernanda",
  "Column2": "DA",
  "Column3": "DA",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DB",
  "Column7": "DA",
  "Column8": "DA",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DA",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": "-",
  "Column18": 80
 },
 {
  "IEM Instituto Técnico Industrial": "Camacho Pineda Juan Esteban",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DA",
  "Column5": "DBJ",
  "Column6": "DB",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DB",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 3,
  "Column18": 71
 },
 {
  "IEM Instituto Técnico Industrial": "Cardona Herrera Sara Valentina",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DBJ",
  "Column11": "DB",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 5,
  "Column18": 67
 },
 {
  "IEM Instituto Técnico Industrial": "Castro Mejía Emmanuel David",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DB",
  "Column7": "DA",
  "Column8": "DA",
  "Column9": "DBJ",
  "Column10": "DBJ",
  "Column11": "DB",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 7,
  "Column18": 62
 },
 {
  "IEM Instituto Técnico Industrial": "Cely González Mateo Andrés",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DB",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DB",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 5,
  "Column18": 64
 },
 {
  "IEM Instituto Técnico Industrial": "Correa Ramírez Paula Mariana",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DB",
  "Column6": "DB",
  "Column7": "DA",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DA",
  "Column12": "DA",
  "Column13": "DA",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 3,
  "Column18": 72
 },
 {
  "IEM Instituto Técnico Industrial": "Cuéllar Téllez Thiago Sebastián",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DB",
  "Column7": "DA",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 2,
  "Column18": 74
 },
 {
  "IEM Instituto Técnico Industrial": "Dueñas Marín Laura Alejandra",
  "Column2": "DA",
  "Column3": "DA",
  "Column4": "DA",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DA",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DS",
  "Column13": "DA",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": 1,
  "Column18": 84
 },
 {
  "IEM Instituto Técnico Industrial": "Fonseca Ríos Gabriel Santiago",
  "Column2": "DS",
  "Column3": "DS",
  "Column4": "DS",
  "Column5": "DS",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DS",
  "Column10": "DS",
  "Column11": "DS",
  "Column12": "DS",
  "Column13": "DA",
  "Column14": "DS",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": "-",
  "Column18": 94
 },
 {
  "IEM Instituto Técnico Industrial": "García Fonseca Emilse Mariana",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DA",
  "Column8": "DB",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DS",
  "Column13": "DB",
  "Column14": "DB",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": "-",
  "Column18": 83
 },
 {
  "IEM Instituto Técnico Industrial": "Hernández Bautista Carlos Andrés",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DB",
  "Column7": "DA",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DB",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 5,
  "Column18": 65
 },
 {
  "IEM Instituto Técnico Industrial": "León Rodríguez Sofía Elizabeth",
  "Column2": "DA",
  "Column3": "DS",
  "Column4": "DB",
  "Column5": "DS",
  "Column6": "DS",
  "Column7": "DA",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 1,
  "Column18": 79
 },
 {
  "IEM Instituto Técnico Industrial": "Maldonado Peña Emiliano Joaquín",
  "Column2": "DA",
  "Column3": "DS",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DA",
  "Column8": "DB",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DA",
  "Column13": "DB",
  "Column14": "DS",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": "-",
  "Column18": 85
 },
 {
  "IEM Instituto Técnico Industrial": "Ordoñez Velásquez Juliana Isabel",
  "Column2": "DA",
  "Column3": "DS",
  "Column4": "DA",
  "Column5": "DS",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DS",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DA",
  "Column13": "DA",
  "Column14": "DA",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": "-",
  "Column18": 89
 },
 {
  "IEM Instituto Técnico Industrial": "Patiño Cruz Martín Alejandro",
  "Column2": "DA",
  "Column3": "DA",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DS",
  "Column7": "DBJ",
  "Column8": "DBJ",
  "Column9": "DB",
  "Column10": "DBJ",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DA",
  "Column14": "DA",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": 4,
  "Column18": 72
 },
 {
  "IEM Instituto Técnico Industrial": "Ríos Bernal Catalina Jimena",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DBJ",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 4,
  "Column18": 71
 },
 {
  "IEM Instituto Técnico Industrial": "TOTALES",
  "Column2": 2,
  "Column3": 13,
  "Column4": 2,
  "Column5": 7,
  "Column6": "-",
  "Column7": 1,
  "Column8": 4,
  "Column9": 7,
  "Column10": 6,
  "Column11": 3,
  "Column12": 7,
  "Column13": 2,
  "Column14": 11,
  "Column15": 1,
  "Column16": "-",
  "Column17": "..."
 },
 {
  "IEM Instituto Técnico Industrial": "Fecha de creación:2024-10-31 07-04"
 },
 {
  "IEM Instituto Técnico Industrial": "NotaEscolar "
 }
],
"1105":[
 {
  "IEM Instituto Técnico Industrial": "Grupo: 1105, Grado: 11",
  "Column2": "Director: Vivas Serna Donny"
 },
 {
  "IEM Instituto Técnico Industrial": "Periodo: 2 de 2024"
 },
 {
  "IEM Instituto Técnico Industrial": "Estudiante",
  "Column2": "Física",
  "Column3": "Quimica",
  "Column4": "Csociales",
  "Column5": "Econ y Pol",
  "Column6": "Artística",
  "Column7": "Ét y Rel",
  "Column8": "Edufísica",
  "Column9": "Lenguaje",
  "Column10": "Inglés",
  "Column11": "Matemáticas",
  "Column12": "Gempresarial",
  "Column13": "Tecnología",
  "Column14": "Filosofia",
  "Column15": "Taller",
  "Column16": "Convivencia",
  "Column17": "mRep",
  "Column18": "pEst"
 },
 {
  "IEM Instituto Técnico Industrial": "Bayona Villasana Jesús Alejandro",
  "Column2": "DB",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DA",
  "Column14": "DA",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 1,
  "Column18": 75
 },
 {
  "IEM Instituto Técnico Industrial": "Cardenas Manjarres Yeferson Stiven",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DBJ",
  "Column5": "DB",
  "Column6": "DBJ",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 8,
  "Column18": 58
 },
 {
  "IEM Instituto Técnico Industrial": "Carrasco Dominguez Marivy Del Valle",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DA",
  "Column8": "DS",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": 1,
  "Column18": 80
 },
 {
  "IEM Instituto Técnico Industrial": "Carrera Garcia Aaron Moises",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DA",
  "Column8": "DS",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DB",
  "Column17": 4,
  "Column18": 70
 },
 {
  "IEM Instituto Técnico Industrial": "Castaño Rodriguez Sofia Neydimar",
  "Column2": "DB",
  "Column3": "DB",
  "Column4": "DBJ",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DB",
  "Column17": 4,
  "Column18": 69
 },
 {
  "IEM Instituto Técnico Industrial": "Castellanos Ospina Yuber Andrey",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DBJ",
  "Column7": "DB",
  "Column8": "DBJ",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DS",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DB",
  "Column17": 8,
  "Column18": 60
 },
 {
  "IEM Instituto Técnico Industrial": "Castillo Camargo Tatiana Alejandra",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 4,
  "Column18": 69
 },
 {
  "IEM Instituto Técnico Industrial": "Cordero Infante Elias Abiezer",
  "Column2": "DA",
  "Column3": "DS",
  "Column4": "DB",
  "Column5": "DS",
  "Column6": "DA",
  "Column7": "DS",
  "Column8": "DS",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DB",
  "Column12": "DA",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 89
 },
 {
  "IEM Instituto Técnico Industrial": "Correa Forero Juan Diego",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DA",
  "Column5": "DB",
  "Column6": "DB",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DB",
  "Column16": "DA",
  "Column17": 6,
  "Column18": 62
 },
 {
  "IEM Instituto Técnico Industrial": "Fernandez Piso Luis Alejandro",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DB",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 8,
  "Column18": 57
 },
 {
  "IEM Instituto Técnico Industrial": "Garcia Coronado Leydi Katerine",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DBJ",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DA",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 9,
  "Column18": 56
 },
 {
  "IEM Instituto Técnico Industrial": "Gomez Silva Miguel Angel",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 5,
  "Column18": 66
 },
 {
  "IEM Instituto Técnico Industrial": "Gragirena Alayon Scarlet Andrea",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DS",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DA",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 86
 },
 {
  "IEM Instituto Técnico Industrial": "Matoma Cortes Andres Mauricio",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DBJ",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 8,
  "Column18": 54
 },
 {
  "IEM Instituto Técnico Industrial": "Mendez Bautista Laura Valentina",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DB",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 86
 },
 {
  "IEM Instituto Técnico Industrial": "Mendoza Patiño Aaron Gabriel",
  "Column2": "DS",
  "Column3": "DA",
  "Column4": "DA",
  "Column5": "DS",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DA",
  "Column9": "DS",
  "Column10": "DS",
  "Column11": "DA",
  "Column12": "DA",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DB",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 90
 },
 {
  "IEM Instituto Técnico Industrial": "Ovalle Gonzalez Albany Mariana",
  "Column2": "DA",
  "Column3": "DA",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DS",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DB",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 86
 },
 {
  "IEM Instituto Técnico Industrial": "Quiroga Malaver Kevin Santiago",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DB",
  "Column7": "DBJ",
  "Column8": "DBJ",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DB",
  "Column17": 9,
  "Column18": 55
 },
 {
  "IEM Instituto Técnico Industrial": "Ramos Castillo Marco David",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DS",
  "Column7": "DB",
  "Column8": "DS",
  "Column9": "DBJ",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DB",
  "Column16": "DB",
  "Column17": 8,
  "Column18": 60
 },
 {
  "IEM Instituto Técnico Industrial": "Rodriguez Chirinos Merbiannys Paola",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DA",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 6,
  "Column18": 64
 },
 {
  "IEM Instituto Técnico Industrial": "Rosado Salgado Walter Eduardo",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DBJ",
  "Column5": "DBJ",
  "Column6": "DBJ",
  "Column7": "DBJ",
  "Column8": "DB",
  "Column9": "DBJ",
  "Column10": "DBJ",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DBJ",
  "Column14": "DBJ",
  "Column15": "DBJ",
  "Column16": "DB",
  "Column17": 12,
  "Column18": 49
 },
 {
  "IEM Instituto Técnico Industrial": "Sanchez Leaño Carol Sammantha",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DA",
  "Column5": "DS",
  "Column6": "DS",
  "Column7": "DA",
  "Column8": "DB",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DA",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 86
 },
 {
  "IEM Instituto Técnico Industrial": "Santarroza Ramirez Yoiner Ismael Josue",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DA",
  "Column5": "DA",
  "Column6": "DS",
  "Column7": "DS",
  "Column8": "DS",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DBJ",
  "Column14": "DA",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 1,
  "Column18": 82
 },
 {
  "IEM Instituto Técnico Industrial": "Silva Rodriguez Angel",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DB",
  "Column5": "DA",
  "Column6": "DA",
  "Column7": "DBJ",
  "Column8": "DS",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DB",
  "Column13": "DS",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": 2,
  "Column18": 78
 },
 {
  "IEM Instituto Técnico Industrial": "Tocarruncho Cardozo Darly Valentina",
  "Column2": "DB",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DB",
  "Column6": "DB",
  "Column7": "DB",
  "Column8": "DB",
  "Column9": "DB",
  "Column10": "DB",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DA",
  "Column14": "DB",
  "Column15": "DA",
  "Column16": "DB",
  "Column17": 3,
  "Column18": 68
 },
 {
  "IEM Instituto Técnico Industrial": "Toro Muñoz Dilan Yohan",
  "Column2": "DA",
  "Column3": "DBJ",
  "Column4": "DB",
  "Column5": "DBJ",
  "Column6": "DA",
  "Column7": "DBJ",
  "Column8": "DA",
  "Column9": "DB",
  "Column10": "DA",
  "Column11": "DBJ",
  "Column12": "DBJ",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DA",
  "Column16": "DA",
  "Column17": 6,
  "Column18": 66
 },
 {
  "IEM Instituto Técnico Industrial": "Vargas Castellano Yeylyn Tatiana",
  "Column2": "DA",
  "Column3": "DB",
  "Column4": "DA",
  "Column5": "DB",
  "Column6": "DA",
  "Column7": "DB",
  "Column8": "DA",
  "Column9": "DA",
  "Column10": "DB",
  "Column11": "DB",
  "Column12": "DB",
  "Column13": "DB",
  "Column14": "DBJ",
  "Column15": "DS",
  "Column16": "DA",
  "Column17": 1,
  "Column18": 76
 },
 {
  "IEM Instituto Técnico Industrial": "Villegas Moncayo Stephania Valentina",
  "Column2": "DA",
  "Column3": "DA",
  "Column4": "DB",
  "Column5": "DS",
  "Column6": "DA",
  "Column7": "DA",
  "Column8": "DA",
  "Column9": "DA",
  "Column10": "DA",
  "Column11": "DA",
  "Column12": "DA",
  "Column13": "DS",
  "Column14": "DA",
  "Column15": "DS",
  "Column16": "DS",
  "Column17": "-",
  "Column18": 87
 },
 {
  "IEM Instituto Técnico Industrial": "TOTALES",
  "Column2": "-",
  "Column3": 14,
  "Column4": 9,
  "Column5": 8,
  "Column6": 5,
  "Column7": 8,
  "Column8": 2,
  "Column9": 9,
  "Column10": 3,
  "Column11": 15,
  "Column12": 14,
  "Column13": 9,
  "Column14": 18,
  "Column15": 2,
  "Column16": "-",
  "Column17": "..."
 },
 {
  "IEM Instituto Técnico Industrial": "Fecha de creación:2024-10-31 07-04"
 },
 {
  "IEM Instituto Técnico Industrial": "NotaEscolar "
 }
]
};
